export const REMOVE_FROM_FAVOURITE = "REMOVE_FROM_FAVOURITE";

export const ADD_TO_FAVOURITE = "ADD_TO_FAVOURITE";

export const STORE_JOBS = "STORE_JOBS";

export const GET_JOBS_LOADING = "GET_JOBS_LOADING";

export const GET_JOBS_ERROR = "GET_JOBS_ERROR";
